[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) in "
disabled = false
show_always = true

[aws]
disabled = true

[conda]
format = "[$symbol$environment](dimmed green) "
disabled = false
